AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Concert Memories

Globals:
  Function:
    Timeout: 20

Resources:

  AccessDynamoDBTablesRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
      AssumeRolePolicyDocument:
        Version: "2012-10-17" 
        Statement: 
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'WriteToCloudWatch'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudwatch:PutMetricData
              Resource: '*'
        - PolicyName: 'AccessConcertsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource: 
                Fn::Join:
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':table/concerts'
        - PolicyName: 'AccessBandsTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource: 
                Fn::Join:
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - !Ref 'AWS::Region'
                    - ':'
                    - !Ref 'AWS::AccountId'
                    - ':table/bands'

  GetConcertLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessDynamoDBTablesRole.Arn
      CodeUri: ConcertMemoriesLambda
      Handler: com.nashss.se.concertmemories.lambda.GetConcertLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        SustainableShipmentService:
          Type: Api
          Properties:
            Path: /concerts/{id}
            Method: get

 #-----------------------------------------------------------------
  
  ConcertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "email_address"
          AttributeType: "S"
     AttributeDefinitions:
        - AttributeName: "date_attended"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email_address"
          KeyType: "HASH"
        - AtributeName: "date_attended"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "concerts"

  BandsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "email_address"
          AttributeType: "S"
        - AttributeName: "band_name"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email_address"
          KeyType: "HASH"
        - AttributeName: "band_name"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "bands"

